-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema p3_parcial
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `p3_parcial` ;

-- -----------------------------------------------------
-- Schema p3_parcial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `p3_parcial` DEFAULT CHARACTER SET utf8 ;
USE `p3_parcial` ;

-- -----------------------------------------------------
-- Table `p3_parcial`.`EX1_TIPOS_LICENCIAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `p3_parcial`.`EX1_TIPOS_LICENCIAS` ;

CREATE TABLE IF NOT EXISTS `p3_parcial`.`EX1_TIPOS_LICENCIAS` (
  `TIPO_LICENCIA_ID` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `DESCRIPCION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`TIPO_LICENCIA_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p3_parcial`.`EX1_CONDUCTORES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `p3_parcial`.`EX1_CONDUCTORES` ;

CREATE TABLE IF NOT EXISTS `p3_parcial`.`EX1_CONDUCTORES` (
  `CONDUCTOR_ID` INT NOT NULL AUTO_INCREMENT,
  `PATERNO` VARCHAR(45) NOT NULL,
  `MATERNO` VARCHAR(45) NULL,
  `NOMBRES` VARCHAR(45) NOT NULL,
  `NUM_LICENCIA` VARCHAR(45) NOT NULL,
  `TIPO_LICENCIA_ID` INT NOT NULL,
  `PUNTOS_ACUMULADOS` INT NOT NULL,
  PRIMARY KEY (`CONDUCTOR_ID`),
  INDEX `fk_EX1_CONDUCTORES_EX1_TIPOS_LICENCIAS_idx` (`TIPO_LICENCIA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_EX1_CONDUCTORES_EX1_TIPOS_LICENCIAS`
    FOREIGN KEY (`TIPO_LICENCIA_ID`)
    REFERENCES `p3_parcial`.`EX1_TIPOS_LICENCIAS` (`TIPO_LICENCIA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p3_parcial`.`EX1_VEHICULOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `p3_parcial`.`EX1_VEHICULOS` ;

CREATE TABLE IF NOT EXISTS `p3_parcial`.`EX1_VEHICULOS` (
  `VEHICULO_ID` INT NOT NULL AUTO_INCREMENT,
  `PLACA` CHAR(7) NOT NULL,
  `MARCA` VARCHAR(45) NOT NULL,
  `MODELO` VARCHAR(45) NOT NULL,
  `ANHO` INT NOT NULL,
  PRIMARY KEY (`VEHICULO_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p3_parcial`.`EX1_INFRACCIONES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `p3_parcial`.`EX1_INFRACCIONES` ;

CREATE TABLE IF NOT EXISTS `p3_parcial`.`EX1_INFRACCIONES` (
  `INFRACCION_ID` INT NOT NULL,
  `DESCRIPCION` VARCHAR(45) NOT NULL,
  `MONTO_MULTA` DECIMAL(10,3) NOT NULL,
  `GRAVEDAD` ENUM('LEVE', 'GRAVE', 'MUY_GRAVE') NOT NULL,
  `PUNTOS` INT NOT NULL,
  PRIMARY KEY (`INFRACCION_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p3_parcial`.`EX1_REPORTES_INFRACCIONES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `p3_parcial`.`EX1_REPORTES_INFRACCIONES` ;

CREATE TABLE IF NOT EXISTS `p3_parcial`.`EX1_REPORTES_INFRACCIONES` (
  `REPORTE_ID` INT NOT NULL AUTO_INCREMENT,
  `CONDUCTOR_ID` INT NOT NULL,
  `PATERNO` VARCHAR(45) NOT NULL,
  `MATERNO` VARCHAR(45) NULL,
  `NOMBRES` VARCHAR(45) NOT NULL,
  `VEHICULO_ID` INT NOT NULL,
  `PLACA` CHAR(7) NOT NULL,
  `MARCA` VARCHAR(45) NOT NULL,
  `MODELO` VARCHAR(45) NOT NULL,
  `ANHO` INT NOT NULL,
  `INFRACCION_ID` INT NOT NULL,
  `DESCRIPCION` VARCHAR(255) NOT NULL,
  `MONTO` DECIMAL(10,3) NOT NULL,
  `GRAVEDAD` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`REPORTE_ID`),
  INDEX `fk_EX1_REPORTES_INFRACCIONES_EX1_CONDUCTORES1_idx` (`CONDUCTOR_ID` ASC) VISIBLE,
  INDEX `fk_EX1_REPORTES_INFRACCIONES_EX1_VEHICULOS1_idx` (`VEHICULO_ID` ASC) VISIBLE,
  INDEX `fk_EX1_REPORTES_INFRACCIONES_EX1_INFRACCIONES1_idx` (`INFRACCION_ID` ASC) VISIBLE,
  CONSTRAINT `fk_EX1_REPORTES_INFRACCIONES_EX1_CONDUCTORES1`
    FOREIGN KEY (`CONDUCTOR_ID`)
    REFERENCES `p3_parcial`.`EX1_CONDUCTORES` (`CONDUCTOR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EX1_REPORTES_INFRACCIONES_EX1_VEHICULOS1`
    FOREIGN KEY (`VEHICULO_ID`)
    REFERENCES `p3_parcial`.`EX1_VEHICULOS` (`VEHICULO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EX1_REPORTES_INFRACCIONES_EX1_INFRACCIONES1`
    FOREIGN KEY (`INFRACCION_ID`)
    REFERENCES `p3_parcial`.`EX1_INFRACCIONES` (`INFRACCION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p3_parcial`.`EX1_VEHICULOS_POR_CONDUCTOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `p3_parcial`.`EX1_VEHICULOS_POR_CONDUCTOR` ;

CREATE TABLE IF NOT EXISTS `p3_parcial`.`EX1_VEHICULOS_POR_CONDUCTOR` (
  `VEHICULO_ID` INT NOT NULL,
  `CONDUCTOR_ID` INT NOT NULL,
  `FECHA_ADQUISICION` DATE NOT NULL,
  PRIMARY KEY (`VEHICULO_ID`, `CONDUCTOR_ID`),
  INDEX `fk_EX1_VEHICULOS_POR_CONDUCTOR_EX1_VEHICULOS1_idx` (`VEHICULO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_EX1_VEHICULOS_POR_CONDUCTOR_EX1_CONDUCTORES1`
    FOREIGN KEY (`CONDUCTOR_ID`)
    REFERENCES `p3_parcial`.`EX1_CONDUCTORES` (`CONDUCTOR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EX1_VEHICULOS_POR_CONDUCTOR_EX1_VEHICULOS1`
    FOREIGN KEY (`VEHICULO_ID`)
    REFERENCES `p3_parcial`.`EX1_VEHICULOS` (`VEHICULO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p3_parcial`.`EX1_REGISTRO_INFRACCIONES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `p3_parcial`.`EX1_REGISTRO_INFRACCIONES` ;

CREATE TABLE IF NOT EXISTS `p3_parcial`.`EX1_REGISTRO_INFRACCIONES` (
  `FECHA` DATE NOT NULL,
  `VEHICULO_ID` INT NOT NULL,
  `CONDUCTOR_ID` INT NOT NULL,
  `INFRACCION_ID` INT NOT NULL,
  PRIMARY KEY (`FECHA`, `VEHICULO_ID`, `CONDUCTOR_ID`, `INFRACCION_ID`),
  INDEX `fk_EX1_REGISTRO_INFRACCIONES_EX1_INFRACCIONES1_idx` (`INFRACCION_ID` ASC) VISIBLE,
  CONSTRAINT `fk_EX1_REGISTRO_INFRACCIONES_EX1_VEHICULOS_POR_CONDUCTOR1`
    FOREIGN KEY (`VEHICULO_ID` , `CONDUCTOR_ID`)
    REFERENCES `p3_parcial`.`EX1_VEHICULOS_POR_CONDUCTOR` (`VEHICULO_ID` , `CONDUCTOR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EX1_REGISTRO_INFRACCIONES_EX1_INFRACCIONES1`
    FOREIGN KEY (`INFRACCION_ID`)
    REFERENCES `p3_parcial`.`EX1_INFRACCIONES` (`INFRACCION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
